# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0003_auto_20170206_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='task',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
