# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0004_appointment_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='task',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
